# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Joseph
email: chrisjosephsongs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cjmusic.github.io/" # the base hostname & protocol for your site
twitter_username: chrisjoseph95
github_username:  cjmusic

# Build settings
markdown: kramdown
